version: '3.8'

services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile  # your main Flask app Dockerfile
    image: jaredraycoleman/jaredraycoleman.com:latest
    ports:
      - "5000:80"
    environment:
      FLASK_ENV: development
      STUDY_BREAK_REPO: https://github.com/jaredraycoleman/study_break.git
