apiVersion: v1
kind: Namespace
metadata:
  name: jared-kubishi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jared-kubishi
  name: jared-kubishi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jared-kubishi-service
      app.kubernetes.io/part-of: jared-kubishi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jared-kubishi-service
        app.kubernetes.io/part-of: jared-kubishi
    spec:
      containers:
        - name: service
          image: jaredraycoleman/jaredraycoleman.com:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DEPLOY_ID
              value: DEPLOYID-32de6def32dca8b3ffe1565fbaafd7ef
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: STUDY_BREAK_REPO
              value: https://github.com/jaredraycoleman/study_break.git
            - name: STUDY_BREAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: study-break-secret
                  key: STUDY_BREAK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  namespace: jared-kubishi
  name: jared-kubishi-service
spec:
  selector:
    app.kubernetes.io/name: jared-kubishi-service
    app.kubernetes.io/part-of: jared-kubishi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jared-kubishi-service-ingress
  namespace: jared-kubishi
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: jared.kubishi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jared-kubishi-service
                port:
                  number: 80
    - host: jaredraycoleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jared-kubishi-service
                port:
                  number: 80
    - host: jrayc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jared-kubishi-service
                port:
                  number: 80
  tls:
    - secretName: jared-kubishi-service-cert
      hosts:
        - jared.kubishi.com
    - secretName: jared-kubishi-service-cert-jaredraycoleman
      hosts:
        - jaredraycoleman.com
    - secretName: jared-kubishi-service-cert-jrayc
      hosts:
        - jrayc.com
